# Generated by Django 5.2.3 on 2026-05-08 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computers", "0007_apprelease_alter_computercommand_command_type"),
        ("shops", "0003_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="computer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="computers.computer",
            ),
        ),
    ]
