# Generated by Django 5.2.3 on 2026-05-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0005_alter_order_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="purchase_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Purchase price for stock valuation",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="shell_display",
            field=models.BooleanField(default=True, help_text="Show in client shell"),
        ),
        migrations.AlterField(
            model_name="product",
            name="original_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Original price for showing discounts in shell",
                max_digits=10,
                null=True,
            ),
        ),
    ]
