# Generated by Django 5.2.3 on 2026-05-25 20:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "billing",
            "0010_userbalance_bonus_balance_userbalance_deposit_money_and_more",
        ),
        ("clubs", "0002_clientgroup_notification_userclubprofile"),
        ("computers", "0015_backfill_computer_club_data"),
        ("shops", "0006_product_purchase_price_product_shell_display_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="applies_discount",
            field=models.BooleanField(
                default=True,
                help_text="Whether club/client discounts apply to this product",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="club",
            field=models.ForeignKey(
                blank=True,
                help_text="Club this product belongs to (tenant isolation)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="clubs.club",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="honest_sign",
            field=models.BooleanField(
                default=False,
                help_text="Честный знак (CRPT) marking required — sale needs Data Matrix scan",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_excise",
            field=models.BooleanField(
                default=False,
                help_text="Подакцизный товар — special fiscal flag for alcohol/tobacco",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="notify_low_stock",
            field=models.BooleanField(
                default=False,
                help_text="Send Telegram alert when stock falls below threshold",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tax_rate",
            field=models.CharField(
                default="vat0",
                help_text="Tax rate code (vat0, vat10, vat20, etc.)",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Combo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Calculated from constituent items at full price",
                        max_digits=12,
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Combo selling price (discounted)",
                        max_digits=12,
                    ),
                ),
                ("applies_discount", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combos",
                        to="clubs.club",
                    ),
                ),
                (
                    "computer_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required if tariff is set (combo price depends on zone)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="combos",
                        to="computers.computergroup",
                    ),
                ),
                (
                    "tariff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="combos",
                        to="billing.tariffplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Combo",
                "verbose_name_plural": "Combos",
                "db_table": "shop_combos",
                "ordering": ["club_id", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "schedule_days",
                    models.CharField(
                        default="1234567",
                        help_text="Days when group is visible/sellable. 1=Mon..7=Sun",
                        max_length=7,
                    ),
                ),
                ("schedule_start", models.TimeField(blank=True, null=True)),
                ("schedule_end", models.TimeField(blank=True, null=True)),
                ("show_in_shell", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_groups",
                        to="clubs.club",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Group",
                "verbose_name_plural": "Product Groups",
                "db_table": "shop_product_groups",
                "ordering": ["club_id", "name"],
                "unique_together": {("club", "name")},
            },
        ),
        migrations.AddField(
            model_name="product",
            name="product_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Product group with schedule (separate from Category)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="shops.productgroup",
            ),
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0"),
                        help_text="0..999999, up to 3 decimal places",
                        max_digits=10,
                        verbose_name="Price",
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True, default="", max_length=13, verbose_name="Barcode"
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "applies_discount",
                    models.BooleanField(default=True, verbose_name="Applies discount"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="clubs.club",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "db_table": "shop_services",
                "ordering": ["club_id", "name"],
            },
        ),
        migrations.CreateModel(
            name="ComboServiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.PositiveIntegerField(default=1)),
                (
                    "price_in_combo",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "combo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_items",
                        to="shops.combo",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shops.service"
                    ),
                ),
            ],
            options={
                "db_table": "shop_combo_service_items",
            },
        ),
        migrations.CreateModel(
            name="ComboProductItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.PositiveIntegerField(default=1)),
                (
                    "price_in_combo",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "combo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_items",
                        to="shops.combo",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shops.product"
                    ),
                ),
            ],
            options={
                "db_table": "shop_combo_product_items",
                "unique_together": {("combo", "product")},
            },
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["club", "is_active"], name="shop_servic_club_id_b25ab4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="comboserviceitem",
            unique_together={("combo", "service")},
        ),
    ]
