# Generated by Django 5.2.3 on 2026-05-25 20:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "billing",
            "0010_userbalance_bonus_balance_userbalance_deposit_money_and_more",
        ),
        ("clubs", "0002_clientgroup_notification_userclubprofile"),
        ("computers", "0015_backfill_computer_club_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("called_at", models.DateTimeField(auto_now_add=True)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True, default="")),
                (
                    "answered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="answered_admin_calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null if Shell session was unauthenticated",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_calls",
                        to="clubs.club",
                    ),
                ),
                (
                    "computer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_calls",
                        to="computers.computer",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_calls",
                        to="billing.shift",
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Call",
                "verbose_name_plural": "Admin Calls",
                "db_table": "admin_calls",
                "ordering": ["-called_at"],
            },
        ),
        migrations.CreateModel(
            name="ClientSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duration_minutes", models.PositiveIntegerField(default=0)),
                ("elapsed_minutes", models.PositiveIntegerField(default=0)),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "postpaid",
                    models.BooleanField(
                        default=False,
                        help_text="True for postpay sessions — pay after play",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("active", "Active"),
                            ("finished", "Finished"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=12,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null = guest session",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_sessions",
                        to="clubs.club",
                    ),
                ),
                (
                    "guest_session",
                    models.ForeignKey(
                        blank=True,
                        help_text="Legacy guest session reference (transitional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="club_session_refs",
                        to="computers.guestsession",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_sessions",
                        to="billing.payment",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_sessions",
                        to="billing.shift",
                    ),
                ),
                (
                    "tariff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_sessions",
                        to="billing.tariffplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Session",
                "verbose_name_plural": "Client Sessions",
                "db_table": "client_sessions",
                "ordering": ["-started_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField()),
                ("comment", models.TextField(blank=True, default="")),
                (
                    "contact_info",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "tip_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tip charged from client's real deposit (not bonus)",
                        max_digits=10,
                    ),
                ),
                ("is_anonymous", models.BooleanField(default=False)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="clubs.club",
                    ),
                ),
                (
                    "computer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to="computers.computer",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to="club_sessions.clientsession",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to="billing.shift",
                    ),
                ),
                (
                    "tip_admin",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who was on shift when tip was given",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_tips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "db_table": "reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionHost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "computer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_hosts",
                        to="computers.computer",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosts",
                        to="club_sessions.clientsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session Host",
                "verbose_name_plural": "Session Hosts",
                "db_table": "session_hosts",
                "ordering": ["session_id", "started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="clientsession",
            index=models.Index(
                fields=["club", "status"], name="client_sess_club_id_2a269b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientsession",
            index=models.Index(
                fields=["client"], name="client_sess_client__b0bb7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientsession",
            index=models.Index(
                fields=["-started_at"], name="client_sess_started_5f7444_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["club", "-created_at"], name="reviews_club_id_3ae55f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["is_read"], name="reviews_is_read_3d393c_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="sessionhost",
            unique_together={("session", "computer")},
        ),
    ]
