# Generated by Django 5.2.3 on 2026-05-25 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clubs", "0002_clientgroup_notification_userclubprofile"),
        ("computers", "0015_backfill_computer_club_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guest_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "guest_phone",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("from_at", models.DateTimeField(verbose_name="Booked from")),
                ("to_at", models.DateTimeField(verbose_name="Booked to")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("finished", "Finished"),
                            ("canceled", "Canceled"),
                            ("redeemed", "Redeemed"),
                        ],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("comment", models.TextField(blank=True, default="")),
                (
                    "hard_booking",
                    models.BooleanField(
                        default=False,
                        help_text="Hard booking: cannot start a session crossing this window",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="clubs.club",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hosts",
                    models.ManyToManyField(
                        related_name="bookings", to="computers.computer"
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookings",
                "db_table": "bookings",
                "ordering": ["-from_at"],
                "indexes": [
                    models.Index(
                        fields=["club", "from_at"], name="bookings_club_id_c8af9d_idx"
                    ),
                    models.Index(fields=["status"], name="bookings_status_51373b_idx"),
                ],
            },
        ),
    ]
