# Generated by Django 5.2.3 on 2026-05-25 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clubs", "0002_clientgroup_notification_userclubprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=40)),
                ("body", models.TextField(blank=True, default="")),
                (
                    "button_text",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("button_url", models.URLField(blank=True, default="")),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        help_text="Min 312×176, opt 624×352, ratio 16:9, max 640 KB",
                        null=True,
                        upload_to="news/",
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("show_from", models.DateTimeField(blank=True, null=True)),
                ("show_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news",
                        to="clubs.club",
                    ),
                ),
            ],
            options={
                "verbose_name": "News",
                "verbose_name_plural": "News",
                "db_table": "content_news",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["club", "is_published", "-created_at"],
                        name="content_new_club_id_475d75_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True, default="")),
                ("is_finished", models.BooleanField(default=False)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="clubs.club",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "finished_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finished_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "db_table": "content_tasks",
                "ordering": ["is_finished", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["club", "is_finished"],
                        name="content_tas_club_id_157389_idx",
                    ),
                    models.Index(
                        fields=["assigned_to", "is_finished"],
                        name="content_tas_assigne_b32384_idx",
                    ),
                ],
            },
        ),
    ]
