# Generated by Django 5.2.3 on 2025-12-20 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComputerMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cpu_usage_percent",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="CPU usage percentage (0-100)",
                        max_digits=5,
                    ),
                ),
                (
                    "cpu_temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="CPU temperature in Celsius",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "ram_used_gb",
                    models.DecimalField(
                        decimal_places=2, help_text="RAM used in GB", max_digits=6
                    ),
                ),
                (
                    "ram_available_gb",
                    models.DecimalField(
                        decimal_places=2, help_text="RAM available in GB", max_digits=6
                    ),
                ),
                (
                    "ram_usage_percent",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="RAM usage percentage (0-100)",
                        max_digits=5,
                    ),
                ),
                (
                    "disk_used_gb",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Disk space used in GB",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "disk_available_gb",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Disk space available in GB",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "network_upload_mbps",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Network upload speed in Mbps",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "network_download_mbps",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Network download speed in Mbps",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When metrics were recorded"
                    ),
                ),
            ],
            options={
                "verbose_name": "Computer Metrics",
                "verbose_name_plural": "Computer Metrics",
                "db_table": "computer_metrics",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Computer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Computer name/identifier",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly name", max_length=255, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Computer description"),
                ),
                (
                    "hardware_id",
                    models.CharField(
                        help_text="Unique hardware identifier generated by C# app (CPU ID + Motherboard Serial + MAC)",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "cpu_model",
                    models.CharField(blank=True, help_text="CPU model", max_length=255),
                ),
                (
                    "cpu_cores",
                    models.PositiveIntegerField(
                        blank=True, help_text="Number of CPU cores", null=True
                    ),
                ),
                (
                    "cpu_threads",
                    models.PositiveIntegerField(
                        blank=True, help_text="Number of CPU threads", null=True
                    ),
                ),
                (
                    "ram_total_gb",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total RAM in GB",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "gpu_model",
                    models.CharField(blank=True, help_text="GPU model", max_length=255),
                ),
                (
                    "storage_total_gb",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total storage in GB",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "os_name",
                    models.CharField(
                        blank=True, help_text="Operating system name", max_length=100
                    ),
                ),
                (
                    "os_version",
                    models.CharField(
                        blank=True, help_text="OS version", max_length=100
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address", null=True
                    ),
                ),
                (
                    "mac_address",
                    models.CharField(
                        blank=True, help_text="MAC address", max_length=17
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ONLINE", "Online"),
                            ("OFFLINE", "Offline"),
                            ("MAINTENANCE", "Maintenance"),
                            ("DISABLED", "Disabled"),
                        ],
                        default="OFFLINE",
                        help_text="Computer status",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Is computer active?"),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        blank=True, help_text="Last time computer was online", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Computer owner/primary user",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="computers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Computer",
                "verbose_name_plural": "Computers",
                "db_table": "computers",
                "ordering": ["-last_seen", "name"],
            },
        ),
        migrations.CreateModel(
            name="ComputerGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_installed",
                    models.BooleanField(
                        default=True, help_text="Is game currently installed?"
                    ),
                ),
                (
                    "install_path",
                    models.CharField(
                        blank=True, help_text="Game installation path", max_length=500
                    ),
                ),
                (
                    "install_size_gb",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Installation size in GB",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "installed_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When game was installed"
                    ),
                ),
                (
                    "last_played",
                    models.DateTimeField(
                        blank=True, help_text="Last time game was played", null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "computer",
                    models.ForeignKey(
                        help_text="Computer",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installed_games",
                        to="computers.computer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Computer Game",
                "verbose_name_plural": "Computer Games",
                "db_table": "computer_games",
                "ordering": ["-last_played", "game__name"],
            },
        ),
    ]
