# Generated by Django 5.2.3 on 2025-12-20 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("computers", "0001_initial"),
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="computergame",
            name="game",
            field=models.ForeignKey(
                help_text="Installed game",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="installations",
                to="games.game",
            ),
        ),
        migrations.AddField(
            model_name="computermetrics",
            name="computer",
            field=models.ForeignKey(
                help_text="Computer",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metrics",
                to="computers.computer",
            ),
        ),
        migrations.AddIndex(
            model_name="computer",
            index=models.Index(fields=["slug"], name="computers_slug_1ca8c9_idx"),
        ),
        migrations.AddIndex(
            model_name="computer",
            index=models.Index(
                fields=["hardware_id"], name="computers_hardwar_4154f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="computer",
            index=models.Index(fields=["owner"], name="computers_owner_i_83de1c_idx"),
        ),
        migrations.AddIndex(
            model_name="computer",
            index=models.Index(fields=["status"], name="computers_status_434d62_idx"),
        ),
        migrations.AddIndex(
            model_name="computer",
            index=models.Index(
                fields=["-last_seen"], name="computers_last_se_49da82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="computergame",
            index=models.Index(
                fields=["computer", "is_installed"],
                name="computer_ga_compute_94abb1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="computergame",
            index=models.Index(fields=["game"], name="computer_ga_game_id_dac9cc_idx"),
        ),
        migrations.AddIndex(
            model_name="computergame",
            index=models.Index(
                fields=["-last_played"], name="computer_ga_last_pl_a1e6a2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="computergame",
            unique_together={("computer", "game")},
        ),
        migrations.AddIndex(
            model_name="computermetrics",
            index=models.Index(
                fields=["computer", "-timestamp"], name="computer_me_compute_d28e2a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="computermetrics",
            index=models.Index(
                fields=["-timestamp"], name="computer_me_timesta_6aea4a_idx"
            ),
        ),
    ]
