# Generated by Django 5.2.3 on 2025-12-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computers", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computer",
            name="hardware_id",
            field=models.CharField(
                blank=True,
                help_text="Unique hardware identifier generated by C# app (CPU ID + Motherboard Serial + MAC)",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
    ]
