# Generated by Django 5.2.3 on 2026-05-07 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("computers", "0004_computercommand"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="computercommand",
            new_name="computer_co_compute_39af2f_idx",
            old_name="computer_commands_computer_status_idx",
        ),
        migrations.RenameIndex(
            model_name="computercommand",
            new_name="computer_co_created_46329b_idx",
            old_name="computer_commands_created_at_idx",
        ),
    ]
