# Generated by Django 5.2.3 on 2026-05-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "computers",
            "0005_rename_computer_commands_computer_status_idx_computer_co_compute_39af2f_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="computer",
            name="pc_number",
            field=models.PositiveIntegerField(
                blank=True, help_text="Computer number in the club", null=True
            ),
        ),
    ]
