# Generated by Django 5.2.3 on 2026-05-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computers", "0006_computer_pc_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Version"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="updates/", verbose_name="Installer File"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Changelog"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "App Release",
                "verbose_name_plural": "App Releases",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="computercommand",
            name="command_type",
            field=models.CharField(
                choices=[
                    ("install", "Install"),
                    ("reinstall", "Reinstall"),
                    ("uninstall", "Uninstall"),
                    ("update", "Update"),
                    ("update_app", "Update Application"),
                ],
                max_length=20,
            ),
        ),
    ]
