# Generated by Django 5.2.3 on 2026-05-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computers", "0007_apprelease_alter_computercommand_command_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="computer",
            name="map_zone",
            field=models.CharField(
                blank=True,
                default="main",
                help_text="Zone name on the map (e.g. VIP, main, console)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="computer",
            name="position_x",
            field=models.IntegerField(
                default=0, help_text="X position on the club map (pixels)"
            ),
        ),
        migrations.AddField(
            model_name="computer",
            name="position_y",
            field=models.IntegerField(
                default=0, help_text="Y position on the club map (pixels)"
            ),
        ),
    ]
