# Generated by Django 5.2.3 on 2026-05-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computers", "0008_add_map_position_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="MapElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "element_type",
                    models.CharField(
                        choices=[
                            ("wall_h", "Стена (горизонтальная)"),
                            ("wall_v", "Стена (вертикальная)"),
                            ("door", "Вход/Выход"),
                            ("wc", "Туалет"),
                            ("bar", "Бар"),
                            ("reception", "Ресепшн"),
                            ("sofa", "Диван"),
                            ("fire", "Огнетушитель"),
                            ("billiard", "Бильярд"),
                            ("console", "Консоль (PS/Xbox)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("position_x", models.IntegerField(default=0)),
                ("position_y", models.IntegerField(default=0)),
                ("width", models.IntegerField(default=40, help_text="Width in pixels")),
                (
                    "height",
                    models.IntegerField(default=40, help_text="Height in pixels"),
                ),
                (
                    "rotation",
                    models.IntegerField(default=0, help_text="Rotation in degrees"),
                ),
            ],
            options={
                "verbose_name": "Map Element",
                "verbose_name_plural": "Map Elements",
                "db_table": "map_elements",
            },
        ),
    ]
