# Generated by Django 5.2.3 on 2026-05-22 11:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computers", "0009_mapelement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computercommand",
            name="command_type",
            field=models.CharField(
                choices=[
                    ("install", "Install"),
                    ("reinstall", "Reinstall"),
                    ("uninstall", "Uninstall"),
                    ("update", "Update"),
                    ("update_app", "Update Application"),
                    ("unlock", "Unlock (Open Access)"),
                    ("lock", "Lock (Close Access)"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="GuestSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "rate_per_hour",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Current hourly rate for this computer",
                        max_digits=10,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Calculated amount at end of session",
                        max_digits=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "computer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_sessions",
                        to="computers.computer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guest Session",
                "verbose_name_plural": "Guest Sessions",
                "db_table": "guest_sessions",
                "ordering": ["-start_time"],
            },
        ),
    ]
