# Generated by Django 5.2.3 on 2026-05-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computers", "0010_alter_computercommand_command_type_guestsession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computercommand",
            name="command_type",
            field=models.CharField(
                choices=[
                    ("install", "Install"),
                    ("reinstall", "Reinstall"),
                    ("uninstall", "Uninstall"),
                    ("update", "Update"),
                    ("update_app", "Update Application"),
                    ("unlock", "Unlock (Open Access)"),
                    ("lock", "Lock (Close Access)"),
                    ("reboot", "Reboot"),
                    ("shutdown", "Shutdown"),
                    ("wol", "Wake on LAN"),
                    ("login", "Login User"),
                    ("transfer", "Transfer Session"),
                ],
                max_length=20,
            ),
        ),
    ]
