# Generated by Django 5.2.3 on 2026-05-25 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0001_initial"),
        ("computers", "0011_alter_computercommand_command_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComputerGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="Name")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, default="", max_length=80, verbose_name="Slug"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6366f1",
                        help_text="Display color of the zone in the UI",
                        max_length=20,
                        verbose_name="Color",
                    ),
                ),
                (
                    "position",
                    models.IntegerField(
                        default=0,
                        help_text="Sort order on the map",
                        verbose_name="Position",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="computer_groups",
                        to="clubs.club",
                        verbose_name="Club",
                    ),
                ),
            ],
            options={
                "verbose_name": "Computer Group",
                "verbose_name_plural": "Computer Groups",
                "db_table": "computer_groups",
                "ordering": ["club_id", "position", "name"],
                "unique_together": {("club", "name")},
            },
        ),
        migrations.AddField(
            model_name="computer",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Computer group / zone inside the club",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="computers",
                to="computers.computergroup",
            ),
        ),
    ]
