# Generated by Django 5.2.3 on 2026-05-25 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0001_initial"),
        ("computers", "0012_computergroup_computer_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="computer",
            name="club",
            field=models.ForeignKey(
                blank=True,
                help_text="Club this computer belongs to. Required for tenant isolation.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="computers",
                to="clubs.club",
            ),
        ),
    ]
