# Generated by Django 5.2.3 on 2026-05-25 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("computers", "0013_add_computer_club_fk"),
    ]

    operations = []
