# Generated by Django 5.2.3 on 2026-05-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computers", "0015_backfill_computer_club_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="computer",
            name="current_app",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Currently active application reported by Shell",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="computer",
            name="shell_version",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Version of installed Shell",
                max_length=32,
            ),
        ),
    ]
