# Generated by Django 5.2.3 on 2026-06-04 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0007_userclubprofile_is_active_userclubprofile_is_guest_and_more"),
        ("computers", "0016_add_runtime_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_admin", models.BooleanField(default=False)),
                (
                    "sender_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("text", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "club",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="clubs.club",
                    ),
                ),
                (
                    "computer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="computers.computer",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "computer_chat_messages",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["computer", "created_at"],
                        name="computer_ch_compute_bf6e62_idx",
                    ),
                    models.Index(
                        fields=["computer", "from_admin", "is_read"],
                        name="computer_ch_compute_648c4a_idx",
                    ),
                ],
            },
        ),
    ]
