# Generated by Django 5.2.3 on 2026-06-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computers", "0017_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="computergame",
            name="installed_version",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Version currently installed on this PC (for auto-update diff).",
                max_length=50,
            ),
        ),
    ]
