# Generated by Django 5.2.3 on 2026-06-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computers", "0018_computergame_installed_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="computer",
            name="high_access_active",
            field=models.BooleanField(
                default=False,
                help_text="High-access (elevated) mode is granted on this PC",
            ),
        ),
        migrations.AlterField(
            model_name="computercommand",
            name="command_type",
            field=models.CharField(
                choices=[
                    ("install", "Install"),
                    ("reinstall", "Reinstall"),
                    ("uninstall", "Uninstall"),
                    ("update", "Update"),
                    ("update_app", "Update Application"),
                    ("unlock", "Unlock (Open Access)"),
                    ("lock", "Lock (Close Access)"),
                    ("reboot", "Reboot"),
                    ("shutdown", "Shutdown"),
                    ("wol", "Wake on LAN"),
                    ("login", "Login User"),
                    ("transfer", "Transfer Session"),
                    ("high_access", "Grant High Access"),
                    ("high_access_off", "Revoke High Access"),
                ],
                max_length=20,
            ),
        ),
    ]
