# Generated by Django 5.2.3 on 2026-06-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computers", "0019_computer_high_access_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computercommand",
            name="command_type",
            field=models.CharField(
                choices=[
                    ("install", "Install"),
                    ("reinstall", "Reinstall"),
                    ("uninstall", "Uninstall"),
                    ("update", "Update"),
                    ("update_app", "Update Application"),
                    ("unlock", "Unlock (Open Access)"),
                    ("lock", "Lock (Close Access)"),
                    ("reboot", "Reboot"),
                    ("shutdown", "Shutdown"),
                    ("wol", "Wake on LAN"),
                    ("login", "Login User"),
                    ("transfer", "Transfer Session"),
                    ("high_access", "Grant High Access"),
                    ("high_access_off", "Revoke High Access"),
                    ("kill_games", "Kill Game Processes"),
                ],
                max_length=20,
            ),
        ),
    ]
