# Generated by Django 5.2.3 on 2026-04-02 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("computers", "0003_alter_computer_hardware_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComputerBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "minutes_remaining",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Remaining play time in minutes",
                        verbose_name="Minutes Remaining",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this computer has access to play",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "computer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance",
                        to="computers.computer",
                        verbose_name="Computer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Computer Balance",
                "verbose_name_plural": "Computer Balances",
                "db_table": "billing_computer_balance",
                "ordering": ["computer__name"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monetary amount received",
                        max_digits=10,
                        verbose_name="Amount Paid",
                    ),
                ),
                (
                    "minutes_added",
                    models.PositiveIntegerField(
                        help_text="Play time granted in minutes",
                        verbose_name="Minutes Added",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Наличные"),
                            ("card", "Карта"),
                            ("transfer", "Перевод"),
                        ],
                        default="cash",
                        max_length=20,
                        verbose_name="Payment Method",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Note")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who processed this payment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="billing_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Admin",
                    ),
                ),
                (
                    "computer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="computers.computer",
                        verbose_name="Computer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "db_table": "billing_payments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["computer"], name="billing_pay_compute_462304_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="billing_pay_created_93e561_idx"
                    ),
                ],
            },
        ),
    ]
