# Generated by Django 5.2.3 on 2026-05-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_tariffplan"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsMetrics",
            fields=[],
            options={
                "verbose_name": "🔍 Аналитика",
                "verbose_name_plural": "🔍 Аналитика",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("billing.payment",),
        ),
    ]
