# Generated by Django 5.2.3 on 2026-05-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0007_abonement_purchasedabonement"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="closing_cash",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount of cash actually present in the register at the end of the shift.",
                max_digits=12,
                null=True,
                verbose_name="Closing Cash (Manual Entry)",
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="total_revenue_card",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="shift",
            name="total_revenue_cash",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="shift",
            name="x_reports_generated",
            field=models.IntegerField(default=0),
        ),
    ]
