# Generated by Django 5.2.3 on 2026-05-25 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0008_shift_closing_cash_shift_total_revenue_card_and_more"),
        ("clubs", "0001_initial"),
        ("computers", "0012_computergroup_computer_group"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tariffplan",
            options={
                "ordering": ["club_id", "tariff_type", "price"],
                "verbose_name": "Tariff Plan",
                "verbose_name_plural": "Tariff Plans",
            },
        ),
        migrations.AddField(
            model_name="tariffplan",
            name="apply_discount",
            field=models.BooleanField(
                default=True, verbose_name="Discounts applicable"
            ),
        ),
        migrations.AddField(
            model_name="tariffplan",
            name="club",
            field=models.ForeignKey(
                blank=True,
                help_text="Club this tariff belongs to. Null = legacy/global.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tariffs",
                to="clubs.club",
                verbose_name="Club",
            ),
        ),
        migrations.AddField(
            model_name="tariffplan",
            name="has_schedule",
            field=models.BooleanField(
                default=False, verbose_name="Has schedule restriction"
            ),
        ),
        migrations.AddField(
            model_name="tariffplan",
            name="is_night",
            field=models.BooleanField(default=False, verbose_name="Night tariff"),
        ),
        migrations.AddField(
            model_name="tariffplan",
            name="life_days",
            field=models.PositiveIntegerField(
                default=0,
                help_text="For SUBSCRIPTION: how many days the bought tariff stays valid",
                verbose_name="Life span (days)",
            ),
        ),
        migrations.AddField(
            model_name="tariffplan",
            name="schedule_days",
            field=models.CharField(
                default="1234567",
                help_text="Days of week the tariff is active. 1=Mon … 7=Sun",
                max_length=7,
                verbose_name="Active days",
            ),
        ),
        migrations.AddField(
            model_name="tariffplan",
            name="schedule_end",
            field=models.TimeField(blank=True, null=True, verbose_name="Schedule end"),
        ),
        migrations.AddField(
            model_name="tariffplan",
            name="schedule_start",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Schedule start"
            ),
        ),
        migrations.AddField(
            model_name="tariffplan",
            name="tariff_type",
            field=models.CharField(
                choices=[
                    ("fixed", "Fixed (e.g. 1 hour)"),
                    ("package", "Package (e.g. Night pack)"),
                    ("per_minute", "Per minute"),
                    ("subscription", "Subscription / Abonement"),
                ],
                default="fixed",
                max_length=20,
                verbose_name="Tariff type",
            ),
        ),
        migrations.AddField(
            model_name="tariffplan",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AddField(
            model_name="tariffplan",
            name="valid_until_time",
            field=models.TimeField(
                blank=True,
                help_text="For PACKAGE: explicit end-of-validity (e.g. 08:00)",
                null=True,
                verbose_name="Valid until (time)",
            ),
        ),
        migrations.AlterField(
            model_name="tariffplan",
            name="minutes",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Granted minutes. For per_minute use 1. For package — until valid_until_time.",
                verbose_name="Duration (minutes)",
            ),
        ),
        migrations.AlterField(
            model_name="tariffplan",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Fallback price if no per-zone TariffPrice rows exist",
                max_digits=10,
                verbose_name="Base price",
            ),
        ),
        migrations.CreateModel(
            name="TariffPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[("day", "Day"), ("night", "Night")],
                        default="day",
                        max_length=10,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tariff_prices",
                        to="computers.computergroup",
                        verbose_name="Computer group / zone",
                    ),
                ),
                (
                    "tariff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="billing.tariffplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tariff Price",
                "verbose_name_plural": "Tariff Prices",
                "db_table": "billing_tariff_prices",
                "ordering": ["tariff_id", "group_id", "period"],
                "unique_together": {("tariff", "group", "period")},
            },
        ),
    ]
