# Generated by Django 5.2.3 on 2026-05-25 20:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0009_alter_tariffplan_options_tariffplan_apply_discount_and_more"),
        ("clubs", "0002_clientgroup_notification_userclubprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userbalance",
            name="bonus_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=12,
                verbose_name="Bonus balance (global fallback)",
            ),
        ),
        migrations.AddField(
            model_name="userbalance",
            name="deposit_money",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Optional global deposit. Per-club deposit lives in UserClubProfile.",
                max_digits=12,
                verbose_name="Deposit (money, global fallback)",
            ),
        ),
        migrations.AlterField(
            model_name="userbalance",
            name="minutes_remaining",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Legacy free minutes counter. Prefer UserClubProfile.deposit_money.",
                verbose_name="Minutes Remaining",
            ),
        ),
        migrations.CreateModel(
            name="CashOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("pko", "Income (ПКО)"), ("rko", "Outcome (РКО)")],
                        max_length=4,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("comment", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_orders",
                        to="clubs.club",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_orders",
                        to="billing.shift",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cash Order",
                "verbose_name_plural": "Cash Orders",
                "db_table": "cash_orders",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["shift", "-created_at"],
                        name="cash_orders_shift_i_0e1005_idx",
                    ),
                    models.Index(
                        fields=["club", "-created_at"],
                        name="cash_orders_club_id_b47579_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Model name or 'system'",
                        max_length=50,
                    ),
                ),
                ("object_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "object_repr",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Human-readable label of the object",
                        max_length=200,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("session.start", "Session started"),
                            ("session.end", "Session ended"),
                            ("session.transfer", "Session transferred"),
                            ("session.penalize", "Session penalized"),
                            ("session.extend", "Session extended"),
                            ("payment.create", "Payment created"),
                            ("payment.refund", "Payment refunded"),
                            ("deposit.topup", "Deposit topped up"),
                            ("deposit.transfer", "Deposit transferred between clubs"),
                            ("cash.pko", "Cash income (ПКО)"),
                            ("cash.rko", "Cash outcome (РКО)"),
                            ("shift.open", "Shift opened"),
                            ("shift.close", "Shift closed"),
                            ("pc.power_on", "PC powered on"),
                            ("pc.power_off", "PC powered off"),
                            ("pc.reboot", "PC rebooted"),
                            ("db.create", "Record created"),
                            ("db.update", "Record updated"),
                            ("db.delete", "Record deleted"),
                            ("auth.login", "Employee logged in"),
                            ("auth.logout", "Employee logged out"),
                        ],
                        max_length=40,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "club",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_logs",
                        to="clubs.club",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operation_logs",
                        to="billing.shift",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who performed the action (operator/system)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Operation Log",
                "verbose_name_plural": "Operation Logs",
                "db_table": "operation_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["club", "-created_at"],
                        name="operation_l_club_id_037e89_idx",
                    ),
                    models.Index(
                        fields=["shift", "-created_at"],
                        name="operation_l_shift_i_272d65_idx",
                    ),
                    models.Index(
                        fields=["action"], name="operation_l_action_23516c_idx"
                    ),
                    models.Index(
                        fields=["object_type", "object_id"],
                        name="operation_l_object__ac28d5_idx",
                    ),
                ],
            },
        ),
    ]
