# Generated by Django 5.2.3 on 2026-05-28 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "billing",
            "0010_userbalance_bonus_balance_userbalance_deposit_money_and_more",
        ),
        ("clubs", "0004_clubsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="club",
            field=models.ForeignKey(
                blank=True,
                help_text="Club where this payment was made",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="clubs.club",
                verbose_name="Club",
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="club",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shifts",
                to="clubs.club",
                verbose_name="Club",
            ),
        ),
    ]
