from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _

from .enums import ComputerStatus


class Computer(models.Model):
    """Computer model - stores PC information and specs"""

    # Basic Information
    name = models.CharField(
        max_length=255, unique=True, help_text=_("Computer name/identifier")
    )
    slug = models.SlugField(
        max_length=255, unique=True, help_text=_("URL-friendly name")
    )
    pc_number = models.PositiveIntegerField(
        null=True, blank=True, help_text=_("Computer number in the club")
    )
    description = models.TextField(blank=True, help_text=_("Computer description"))

    # Unique Hardware Identifier
    hardware_id = models.CharField(
        max_length=64,
        unique=True,
        null=True,
        blank=True,
        help_text=_(
            "Unique hardware identifier generated by C# app (CPU ID + Motherboard Serial + MAC)"
        ),
    )

    # Owner/Account
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="computers",
        help_text=_("Computer owner/primary user"),
    )

    # Club + zoning (Club is mandatory for tenant isolation; group is optional zoning inside the club)
    club = models.ForeignKey(
        "clubs.Club",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="computers",
        help_text=_("Club this computer belongs to. Required for tenant isolation."),
    )
    group = models.ForeignKey(
        "computers.ComputerGroup",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="computers",
        help_text=_("Computer group / zone inside the club"),
    )

    # Hardware Specifications
    cpu_model = models.CharField(max_length=255, blank=True, help_text=_("CPU model"))
    cpu_cores = models.PositiveIntegerField(
        null=True, blank=True, help_text=_("Number of CPU cores")
    )
    cpu_threads = models.PositiveIntegerField(
        null=True, blank=True, help_text=_("Number of CPU threads")
    )

    ram_total_gb = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        null=True,
        blank=True,
        help_text=_("Total RAM in GB"),
    )

    gpu_model = models.CharField(max_length=255, blank=True, help_text=_("GPU model"))
    storage_total_gb = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        null=True,
        blank=True,
        help_text=_("Total storage in GB"),
    )

    # Operating System
    os_name = models.CharField(
        max_length=100, blank=True, help_text=_("Operating system name")
    )
    os_version = models.CharField(max_length=100, blank=True, help_text=_("OS version"))

    # Network
    ip_address = models.GenericIPAddressField(
        null=True, blank=True, help_text=_("IP address")
    )
    mac_address = models.CharField(
        max_length=17, blank=True, help_text=_("MAC address")
    )

    # Status
    status = models.CharField(
        max_length=20,
        choices=ComputerStatus.choices,
        default=ComputerStatus.OFFLINE,
        help_text=_("Computer status"),
    )
    is_active = models.BooleanField(default=True, help_text=_("Is computer active?"))

    # High-access mode: operator-granted elevated desktop access (kiosk lockdown
    # dropped + Windows shell restored). Toggled from the admin; the shell applies
    # it via a high_access / high_access_off command.
    high_access_active = models.BooleanField(
        default=False, help_text=_("High-access (elevated) mode is granted on this PC")
    )

    # Map Position (for interactive club map)
    position_x = models.IntegerField(
        default=0, help_text=_("X position on the club map (pixels)")
    )
    position_y = models.IntegerField(
        default=0, help_text=_("Y position on the club map (pixels)")
    )
    map_zone = models.CharField(
        max_length=50, blank=True, default="main",
        help_text=_("Zone name on the map (e.g. VIP, main, console)")
    )

    # Last Activity
    last_seen = models.DateTimeField(
        null=True, blank=True, help_text=_("Last time computer was online")
    )

    # Runtime state reported by C# Shell (heartbeat)
    current_app = models.CharField(
        max_length=255, blank=True, default="",
        help_text=_("Currently active application reported by Shell"),
    )
    shell_version = models.CharField(
        max_length=32, blank=True, default="",
        help_text=_("Version of installed Shell"),
    )

    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "computers"
        verbose_name = _("Computer")
        verbose_name_plural = _("Computers")
        ordering = ["-last_seen", "name"]
        indexes = [
            models.Index(fields=["slug"]),
            models.Index(fields=["hardware_id"]),
            models.Index(fields=["owner"]),
            models.Index(fields=["status"]),
            models.Index(fields=["-last_seen"]),
        ]

    def __str__(self):
        return self.name

    @property
    def installed_games_count(self):
        """Get number of installed games"""
        return self.installed_games.filter(is_installed=True).count()

    @property
    def total_gaming_hours(self):
        """Get total gaming hours on this computer"""
        from django.db.models import Sum

        result = self.game_sessions.aggregate(total=Sum("total_hours_played"))
        return result["total"] or 0

    @property
    def latest_metrics(self):
        """Get latest computer metrics"""
        return self.metrics.order_by("-timestamp").first()

    def update_status(self, status: str):
        """Update computer status"""
        from django.utils import timezone

        self.status = status
        if status == ComputerStatus.ONLINE:
            self.last_seen = timezone.now()
        self.save(update_fields=["status", "last_seen"])
