# Generated by Django 5.2.3 on 2026-05-09 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_date_of_birth_customuser_profile_image"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="customuser",
            name="user_must_have_email_or_phone",
        ),
    ]
