# Generated by Django 5.2.3 on 2026-05-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_customuser_user_must_have_email_or_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="active_hardware_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
