# Generated by Django 5.2.3 on 2026-05-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customuser_active_hardware_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="last_activity",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
