# Generated by Django 5.2.3 on 2026-05-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_customuser_last_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("owner", "Владелец"),
                    ("manager", "Менеджер"),
                    ("operator", "Оператор"),
                    ("admin", "Администратор"),
                    ("user", "Пользователь"),
                ],
                default="user",
                max_length=10,
            ),
        ),
    ]
