# Generated by Django 5.2.3 on 2025-12-20 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("computers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "steam_app_id",
                    models.BigIntegerField(help_text="Steam App ID", unique=True),
                ),
                ("name", models.CharField(help_text="Game name", max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly game name", max_length=255, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Game description"),
                ),
                (
                    "icon_url",
                    models.URLField(
                        blank=True, help_text="Game icon URL", max_length=500
                    ),
                ),
                (
                    "header_image_url",
                    models.URLField(
                        blank=True, help_text="Header/banner image URL", max_length=500
                    ),
                ),
                (
                    "developer",
                    models.CharField(
                        blank=True, help_text="Game developer", max_length=255
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True, help_text="Game publisher", max_length=255
                    ),
                ),
                (
                    "release_date",
                    models.DateField(blank=True, help_text="Release date", null=True),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Is game active?"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Game",
                "verbose_name_plural": "Games",
                "db_table": "games",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["steam_app_id"], name="games_steam_a_fe4f6d_idx"
                    ),
                    models.Index(fields=["slug"], name="games_slug_076f39_idx"),
                    models.Index(fields=["is_active"], name="games_is_acti_f4d375_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_hours_played",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total hours played (cumulative)",
                        max_digits=10,
                    ),
                ),
                (
                    "current_session_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="When current session started (null if not playing)",
                        null=True,
                    ),
                ),
                (
                    "session_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                            ("ENDED", "Ended"),
                        ],
                        default="ENDED",
                        help_text="Current session status",
                        max_length=10,
                    ),
                ),
                (
                    "last_played",
                    models.DateTimeField(
                        auto_now=True, help_text="Last time this game was played"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        help_text="Player account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "computer",
                    models.ForeignKey(
                        help_text="Computer where game is played",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_sessions",
                        to="computers.computer",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        help_text="Game being played",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="games.game",
                    ),
                ),
            ],
            options={
                "verbose_name": "Game Session",
                "verbose_name_plural": "Game Sessions",
                "db_table": "game_sessions",
                "ordering": ["-last_played"],
                "indexes": [
                    models.Index(
                        fields=["account", "game"],
                        name="game_sessio_account_05f375_idx",
                    ),
                    models.Index(
                        fields=["computer", "game"],
                        name="game_sessio_compute_3f1cef_idx",
                    ),
                    models.Index(
                        fields=["session_status"], name="game_sessio_session_23c092_idx"
                    ),
                    models.Index(
                        fields=["-last_played"], name="game_sessio_last_pl_8735b2_idx"
                    ),
                ],
                "unique_together": {("account", "game", "computer")},
            },
        ),
    ]
