# Generated by Django 5.2.3 on 2025-12-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="header_image_url",
        ),
        migrations.RemoveField(
            model_name="game",
            name="icon_url",
        ),
        migrations.AddField(
            model_name="game",
            name="header_image",
            field=models.ImageField(
                blank=True,
                help_text="Header/banner image",
                null=True,
                upload_to="games/headers/",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="icon",
            field=models.ImageField(
                blank=True, help_text="Game icon", null=True, upload_to="games/icons/"
            ),
        ),
    ]
