# Generated by Django 5.2.3 on 2025-12-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_remove_game_header_image_url_remove_game_icon_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Tag name (e.g., Action, RPG, Multiplayer)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly tag name", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Tag description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Game Tag",
                "verbose_name_plural": "Game Tags",
                "db_table": "game_tags",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="game",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Game tags/genres",
                related_name="games",
                to="games.tag",
            ),
        ),
    ]
