# Generated by Django 5.2.3 on 2026-04-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_game_type_executable_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="text_image",
            field=models.ImageField(
                blank=True,
                help_text="Stylized text/logo image shown as the game title on the dashboard",
                null=True,
                upload_to="games/text_logos/",
            ),
        ),
    ]
