# Generated by Django 5.2.3 on 2026-05-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0005_game_text_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="arguments",
            field=models.CharField(
                blank=True,
                help_text="Command line arguments for the game (e.g. --incognito for Chrome)",
                max_length=500,
                null=True,
            ),
        ),
    ]
