# Generated by Django 5.2.3 on 2026-05-22 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0006_game_arguments"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Имя категории"),
                ),
                ("slug", models.SlugField(unique=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Категория игр/приложений",
                "verbose_name_plural": "Категории игр/приложений",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ClubAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("steam", "Steam"),
                            ("epic", "Epic Games"),
                            ("riot", "Riot Games"),
                            ("battlenet", "Battle.net"),
                            ("origin", "Origin / EA app"),
                            ("ubisoft", "Ubisoft Connect"),
                            ("rockstar", "Rockstar Games Launcher"),
                            ("local", "Local App (No DRM)"),
                        ],
                        max_length=20,
                        verbose_name="Платформа",
                    ),
                ),
                (
                    "login",
                    models.CharField(
                        max_length=255, verbose_name="Логин (Email/Username)"
                    ),
                ),
                ("password", models.CharField(max_length=255, verbose_name="Пароль")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "is_in_use",
                    models.BooleanField(default=False, verbose_name="В использовании"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Клубный аккаунт",
                "verbose_name_plural": "Клубные аккаунты",
                "ordering": ["platform", "login"],
            },
        ),
        migrations.RemoveIndex(
            model_name="game",
            name="games_steam_a_fe4f6d_idx",
        ),
        migrations.RemoveField(
            model_name="game",
            name="game_type",
        ),
        migrations.RemoveField(
            model_name="game",
            name="steam_app_id",
        ),
        migrations.AddField(
            model_name="game",
            name="app_id",
            field=models.CharField(
                blank=True,
                help_text="Внутренний идентификатор игры во внешнем DRM",
                max_length=255,
                null=True,
                verbose_name="App ID (Steam/Epic/etc)",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="is_senet_library",
            field=models.BooleanField(
                default=False,
                help_text="Официальная карточка SENET, защищена от перезаписи ключей.",
                verbose_name="Из Библиотеки SENET",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="platform",
            field=models.CharField(
                choices=[
                    ("steam", "Steam"),
                    ("epic", "Epic Games"),
                    ("riot", "Riot Games"),
                    ("battlenet", "Battle.net"),
                    ("origin", "Origin / EA app"),
                    ("ubisoft", "Ubisoft Connect"),
                    ("rockstar", "Rockstar Games Launcher"),
                    ("local", "Local App (No DRM)"),
                ],
                default="steam",
                max_length=20,
                verbose_name="Платформа запуска",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="games.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["app_id"], name="games_app_id_54fe48_idx"),
        ),
        migrations.AddField(
            model_name="clubaccount",
            name="games",
            field=models.ManyToManyField(
                blank=True,
                related_name="club_accounts",
                to="games.game",
                verbose_name="Игры на аккаунте",
            ),
        ),
    ]
