# Generated by Django 5.2.3 on 2026-06-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0007_category_clubaccount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="version",
            field=models.CharField(
                blank=True,
                default="1.0",
                help_text="Target version; bump it to roll an update to every PC.",
                max_length=50,
            ),
        ),
    ]
