# Generated by Django 5.2.3 on 2026-06-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0008_game_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="header_image_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="External cover URL (used when no uploaded header_image).",
                max_length=1000,
            ),
        ),
    ]
