# Generated by Django 5.2.3 on 2026-05-25 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clubs", "0003_subscriptionplan_club_is_verified_clubnetwork_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShellSecurity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "high_access_password",
                    models.CharField(
                        default="pasw0rd",
                        help_text="Password to enter Ctrl+Alt+P high-access mode. Change from default!",
                        max_length=128,
                    ),
                ),
                ("tightvnc_enabled", models.BooleanField(default=False)),
                (
                    "hidden_drives",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of drive letters hidden in Shell, e.g. ['C', 'D']",
                    ),
                ),
                ("block_external_storage", models.BooleanField(default=False)),
                ("block_chrome_downloads", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shell_security",
                        to="clubs.club",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shell Security",
                "verbose_name_plural": "Shell Security",
                "db_table": "shell_security",
            },
        ),
        migrations.CreateModel(
            name="BlockedApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_mask",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Window title mask, supports wildcard '*' (e.g. *SmartShell*)",
                        max_length=200,
                    ),
                ),
                (
                    "window_class",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Window class (e.g. CabinetWClass, ConsoleWindowClass)",
                        max_length=120,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                (
                    "security",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_apps",
                        to="integrations.shellsecurity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blocked App",
                "verbose_name_plural": "Blocked Apps",
                "db_table": "shell_blocked_apps",
            },
        ),
        migrations.CreateModel(
            name="ShellTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="shell/logo/"),
                ),
                (
                    "poster",
                    models.ImageField(blank=True, null=True, upload_to="shell/poster/"),
                ),
                ("primary_color", models.CharField(default="#6366f1", max_length=20)),
                ("accent_color", models.CharField(default="#a855f7", max_length=20)),
                ("secondary_color", models.CharField(default="#ec4899", max_length=20)),
                (
                    "splash_type",
                    models.CharField(
                        choices=[
                            ("soft", "Soft"),
                            ("snowflake", "SnowFlake"),
                            ("smartlock_tv", "SmartLock TV"),
                        ],
                        default="soft",
                        max_length=20,
                    ),
                ),
                ("splash_enabled", models.BooleanField(default=True)),
                ("splash_delay_seconds", models.PositiveIntegerField(default=60)),
                (
                    "background_image",
                    models.ImageField(blank=True, null=True, upload_to="shell/bg/"),
                ),
                ("tint_effect", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shell_theme",
                        to="clubs.club",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shell Theme",
                "verbose_name_plural": "Shell Themes",
                "db_table": "shell_themes",
            },
        ),
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("telegram", "Telegram"),
                            ("cloudpayments", "CloudPayments"),
                            ("sbp", "СБП (Russia)"),
                            ("kaspi_qr", "Kaspi QR (Kazakhstan)"),
                            ("kaspi_online", "Kaspi Online"),
                            ("stripe", "Stripe"),
                            ("kkm", "Cash register (Kkm-Server)"),
                            ("smartgamer", "SmartGamer mobile"),
                            ("smartkiosk", "SmartKiosk"),
                            ("hardware_controller", "Hardware controller"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Type-specific configuration (api keys, secrets, options)",
                    ),
                ),
                (
                    "notify_event_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Which event types to send (sale, stock_low, review, etc.)",
                    ),
                ),
                ("last_test_at", models.DateTimeField(blank=True, null=True)),
                ("last_test_ok", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrations",
                        to="clubs.club",
                    ),
                ),
            ],
            options={
                "verbose_name": "Integration",
                "verbose_name_plural": "Integrations",
                "db_table": "integrations",
                "ordering": ["club_id", "type"],
                "unique_together": {("club", "type")},
            },
        ),
    ]
