# Generated by Django 5.2.3 on 2026-05-25 20:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "billing",
            "0010_userbalance_bonus_balance_userbalance_deposit_money_and_more",
        ),
        ("clubs", "0002_clientgroup_notification_userclubprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "icon",
                    models.ImageField(blank=True, null=True, upload_to="achievements/"),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("registration", "On registration"),
                            ("topup_single", "Single topup ≥ threshold"),
                            ("topup_total", "Total topup ≥ threshold"),
                            ("spend_single", "Single spend ≥ threshold"),
                            ("spend_total", "Total spend ≥ threshold"),
                            ("hours_in_club", "Total hours in club ≥ threshold"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Threshold value to unlock the achievement",
                        max_digits=12,
                    ),
                ),
                (
                    "reward_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("discount", "Personal discount %"),
                            ("bonus", "Bonus deposit"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                (
                    "reward_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Percent for DISCOUNT, money for BONUS, ignored for NONE",
                        max_digits=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="clubs.club",
                    ),
                ),
            ],
            options={
                "verbose_name": "Achievement",
                "verbose_name_plural": "Achievements",
                "db_table": "loyalty_achievements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Promocode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(blank=True, default="", max_length=120)),
                (
                    "reward_type",
                    models.CharField(
                        choices=[
                            ("discount", "Discount %"),
                            ("deposit_topup", "Top up deposit (money)"),
                            ("bonus_topup", "Top up bonus balance"),
                        ],
                        default="discount",
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Percent for DISCOUNT, money amount for DEPOSIT/BONUS topup",
                        max_digits=10,
                    ),
                ),
                ("applies_to_tariffs", models.BooleanField(default=True)),
                ("applies_to_products", models.BooleanField(default=True)),
                ("applies_to_services", models.BooleanField(default=True)),
                ("applies_to_combos", models.BooleanField(default=True)),
                (
                    "channels",
                    models.JSONField(
                        default=list,
                        help_text="Allowed channels: ['admin','mobile','shell']",
                    ),
                ),
                (
                    "usage_limit",
                    models.PositiveIntegerField(default=0, help_text="0 = unlimited"),
                ),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("telegram_notify_on_use", models.BooleanField(default=False)),
                ("telegram_notify_on_expire", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="If set — only members of this group; otherwise all clients",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="targeted_promocodes",
                        to="clubs.clientgroup",
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promocodes",
                        to="clubs.club",
                    ),
                ),
                (
                    "specific_clients",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific clients only (if set, overrides group)",
                        related_name="targeted_promocodes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Promocode",
                "verbose_name_plural": "Promocodes",
                "db_table": "loyalty_promocodes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromocodeUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("used_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promocode_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promocode_usages",
                        to="billing.payment",
                    ),
                ),
                (
                    "promocode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="loyalty.promocode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promocode Usage",
                "verbose_name_plural": "Promocode Usages",
                "db_table": "loyalty_promocode_usages",
                "ordering": ["-used_at"],
            },
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unlocked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unlocked_by",
                        to="loyalty.achievement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Achievement",
                "verbose_name_plural": "User Achievements",
                "db_table": "loyalty_user_achievements",
                "ordering": ["-unlocked_at"],
            },
        ),
        migrations.CreateModel(
            name="CashbackRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=120)),
                (
                    "deposit_threshold",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Topup threshold"
                    ),
                ),
                (
                    "accrual_type",
                    models.CharField(
                        choices=[("percent", "Percent"), ("fixed", "Fixed amount")],
                        default="percent",
                        max_length=10,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percent (e.g. 5) or fixed money amount",
                        max_digits=10,
                        verbose_name="Value",
                    ),
                ),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cashback_rules",
                        to="clubs.club",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cashback Rule",
                "verbose_name_plural": "Cashback Rules",
                "db_table": "loyalty_cashback_rules",
                "ordering": ["club_id", "deposit_threshold"],
                "unique_together": {("club", "deposit_threshold")},
            },
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                (
                    "percent",
                    models.PositiveSmallIntegerField(
                        help_text="0..100 discount percent", verbose_name="Percent"
                    ),
                ),
                (
                    "schedule_days",
                    models.CharField(
                        default="1234567",
                        help_text="Days when discount is active. 1=Mon..7=Sun",
                        max_length=7,
                    ),
                ),
                ("schedule_start", models.TimeField(blank=True, null=True)),
                ("schedule_end", models.TimeField(blank=True, null=True)),
                ("telegram_notify", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="clubs.club",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discount",
                "verbose_name_plural": "Discounts",
                "db_table": "loyalty_discounts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["club", "is_active"],
                        name="loyalty_dis_club_id_5a5916_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="promocode",
            index=models.Index(
                fields=["club", "is_active"], name="loyalty_pro_club_id_aed3c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promocode",
            index=models.Index(fields=["code"], name="loyalty_pro_code_032f9b_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="promocodeusage",
            unique_together={("promocode", "client")},
        ),
        migrations.AlterUniqueTogether(
            name="userachievement",
            unique_together={("achievement", "user")},
        ),
    ]
