# Generated by Django 5.2.3 on 2026-05-25 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Club name")),
                (
                    "site",
                    models.URLField(
                        blank=True, default="", verbose_name="Site or social"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="Country"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="City"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Asia/Tashkent", max_length=64, verbose_name="Timezone"
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="Street"
                    ),
                ),
                (
                    "house",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="House"
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="Contact name",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=32,
                        verbose_name="Contact phone",
                    ),
                ),
                ("is_trial", models.BooleanField(default=True, verbose_name="Trial")),
                (
                    "trial_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Trial ends at"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_clubs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Club",
                "verbose_name_plural": "Clubs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClubMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("manager", "Manager"),
                            ("operator", "Operator"),
                            ("accountant", "Accountant"),
                            ("sysadmin", "SysAdmin"),
                            ("marketer", "Marketer"),
                            ("other", "Other"),
                        ],
                        default="operator",
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="clubs.club",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Club Membership",
                "verbose_name_plural": "Club Memberships",
                "ordering": ["-created_at"],
                "unique_together": {("user", "club")},
            },
        ),
    ]
