# Generated by Django 5.2.3 on 2026-05-25 20:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16, verbose_name="Name")),
                (
                    "percent_discount",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="0..100, applied as a fallback when client has no personal discount",
                        verbose_name="Discount %",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_groups",
                        to="clubs.club",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Group",
                "verbose_name_plural": "Client Groups",
                "db_table": "client_groups",
                "ordering": ["club_id", "name"],
                "unique_together": {("club", "name")},
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("admin_call", "Admin call from client"),
                            ("sale", "Sale notification"),
                            ("booking", "Booking notification"),
                            ("stock_low", "Stock low warning"),
                            ("session", "Session event"),
                            ("system", "System"),
                        ],
                        default="system",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("body", models.TextField(blank=True, default="")),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "club",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="clubs.club",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-sent_at"],
                        name="notificatio_user_id_f380a0_idx",
                    ),
                    models.Index(
                        fields=["club", "-sent_at"],
                        name="notificatio_club_id_8377e0_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserClubProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deposit_money",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Real money on the deposit, in club currency",
                        max_digits=12,
                        verbose_name="Deposit (money)",
                    ),
                ),
                (
                    "bonus_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Bonus credits earned via cashback/promocodes",
                        max_digits=12,
                        verbose_name="Bonus balance",
                    ),
                ),
                (
                    "personal_discount",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="0..100 — overrides group discount if both set (max wins)",
                        verbose_name="Personal discount %",
                    ),
                ),
                ("is_blocked", models.BooleanField(default=False)),
                ("comment", models.TextField(blank=True, default="")),
                (
                    "important_comment",
                    models.BooleanField(
                        default=False,
                        help_text="If true, comment is highlighted in sale dialog",
                    ),
                ),
                ("last_visit_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_profiles",
                        to="clubs.club",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="members",
                        to="clubs.clientgroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Club Profile",
                "verbose_name_plural": "User Club Profiles",
                "db_table": "user_club_profiles",
                "ordering": ["-last_visit_at"],
                "unique_together": {("user", "club")},
            },
        ),
    ]
