# Generated by Django 5.2.3 on 2026-05-25 21:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0002_clientgroup_notification_userclubprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("starter", "Starter"),
                            ("business", "Business"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "monthly_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "max_pcs",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="0 = unlimited; limit applied to total active Computer count per club",
                    ),
                ),
                ("features", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
                "db_table": "subscription_plans",
                "ordering": ["monthly_price"],
            },
        ),
        migrations.AddField(
            model_name="club",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="Required for online payments and SmartGamer search",
                verbose_name="Verified",
            ),
        ),
        migrations.CreateModel(
            name="ClubNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                (
                    "max_personal_discount",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Cap for personal discounts inside this network (0..100)",
                    ),
                ),
                ("allow_deposit_transfer", models.BooleanField(default=True)),
                (
                    "sync_apps_from_main",
                    models.BooleanField(
                        default=False,
                        help_text="Copy game/app cards from main_club to others",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "main_club",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="main_for_networks",
                        to="clubs.club",
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_network",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Club Network",
                "verbose_name_plural": "Club Networks",
                "db_table": "club_networks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="club",
            name="network",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clubs",
                to="clubs.clubnetwork",
            ),
        ),
        migrations.CreateModel(
            name="ClubSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("trial", "Trial"),
                            ("promised", "Promised payment"),
                            ("expired", "Expired (Free)"),
                            ("blocked", "Blocked (>37 days unpaid)"),
                        ],
                        default="trial",
                        max_length=12,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("auto_renew", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="clubs.club",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="club_subscriptions",
                        to="clubs.subscriptionplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Club Subscription",
                "verbose_name_plural": "Club Subscriptions",
                "db_table": "club_subscriptions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="PromisedPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fee_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("500"), max_digits=10
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("due_at", models.DateTimeField()),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promised_payments",
                        to="clubs.clubsubscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promised Payment",
                "verbose_name_plural": "Promised Payments",
                "db_table": "promised_payments",
                "ordering": ["-granted_at"],
            },
        ),
    ]
