# Generated by Django 5.2.3 on 2026-05-27 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0003_subscriptionplan_club_is_verified_clubnetwork_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClubSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="All operational settings as a JSON object",
                        verbose_name="Settings data",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="clubs.club",
                        verbose_name="Club",
                    ),
                ),
            ],
            options={
                "verbose_name": "Club Settings",
                "verbose_name_plural": "Club Settings",
            },
        ),
    ]
