# Generated by Django 5.2.3 on 2026-05-30 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0005_club_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="club_token",
            field=models.CharField(
                blank=True,
                help_text="8-char code printed on the shell setup screen so PC auto-links to this club",
                max_length=8,
                unique=True,
                verbose_name="Club token",
            ),
        ),
        migrations.CreateModel(
            name="ClientComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Comment")),
                ("is_important", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="written_client_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_comments",
                        to="clubs.club",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Comment",
                "verbose_name_plural": "Client Comments",
                "db_table": "client_comments",
                "ordering": ["-is_important", "-created_at"],
            },
        ),
    ]
