# Generated by Django 5.2.3 on 2026-06-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0006_alter_club_club_token_clientcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="userclubprofile",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Session active"),
        ),
        migrations.AddField(
            model_name="userclubprofile",
            name="is_guest",
            field=models.BooleanField(
                default=False,
                help_text="True when this profile is an anonymous walk-in (no real client).",
                verbose_name="Guest session",
            ),
        ),
        migrations.AddField(
            model_name="userclubprofile",
            name="minutes_remaining",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Playable minutes purchased at THIS club.",
                verbose_name="Minutes remaining (this club)",
            ),
        ),
        migrations.AddField(
            model_name="userclubprofile",
            name="postpaid_minutes",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Minutes played on credit in the current postpaid session.",
                verbose_name="Postpaid minutes (debt)",
            ),
        ),
        migrations.AddField(
            model_name="userclubprofile",
            name="postpaid_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Postpaid rate (per hour)",
            ),
        ),
        migrations.AddField(
            model_name="userclubprofile",
            name="postpaid_started_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Postpaid started at"
            ),
        ),
        migrations.AddField(
            model_name="userclubprofile",
            name="session_mode",
            field=models.CharField(
                choices=[("prepaid", "Предоплата"), ("postpaid", "Постоплата")],
                default="prepaid",
                max_length=10,
                verbose_name="Session mode",
            ),
        ),
    ]
