# Generated by Django 5.2.3 on 2026-06-05 14:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0007_userclubprofile_is_active_userclubprofile_is_guest_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClubWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Balance",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "club",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to="clubs.club",
                    ),
                ),
            ],
            options={
                "verbose_name": "Club Wallet",
                "verbose_name_plural": "Club Wallets",
                "db_table": "club_wallets",
            },
        ),
        migrations.CreateModel(
            name="ClubWalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("topup", "Top-up"),
                            ("charge", "Subscription charge"),
                            ("refund", "Refund"),
                            ("adjust", "Manual adjustment"),
                        ],
                        max_length=12,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=12)),
                ("comment", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="club_wallet_txns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="clubs.clubwallet",
                    ),
                ),
            ],
            options={
                "db_table": "club_wallet_transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["wallet", "created_at"],
                        name="club_wallet_wallet__6cf0a1_idx",
                    )
                ],
            },
        ),
    ]
